### ISSUE TITLE
見る人がよりやさしい世界へ近づける

### ISSUE THREAD

**Issue by tomoya-tsuji** [sdevtalks/sdevtalks.org#58]
- [ ] 今開いてるページのmenuにactiveであること伝えるために色変える
- [ ] ボタンhover時のスタイル当てる
- [ ] headerのtwitterアイコンをshareと違うようにする
   - 同じアイコンなのに、役割違うの違和感ある
- [ ] 別タブで開くボタンにはアイコンつけたい

**Comment by tomoya-tsuji** [comment]
- [ ] ページ内アンカーをつける

**Comment by s-osa** [comment]
> 別タブで開くボタンにはアイコンつけたい

```css
content: 'open_in_new';
```

してるところで、`target="blank"` してないところでもアイコンフォントが挿入されてる。
（例：イベント詳細ページの Connpass リンクボタン）

これを避けるために、

```css
&[target="blank"]:after {
  content: 'open_in_new';
}
```

的なことが必要そう。

あと、target blank じゃないときは padding も変わりそうなので結構めんどい……？
